name: Deploy to Test

on:
  workflow_run:
    workflows: [Docker]
    types: [completed]
    branches: [master]
  workflow_dispatch:

jobs:
  deploy-to-test:
    uses: ./.github/workflows/deploy-to-env.yml
    with:
      k8s_namespace: grif-test
    secrets:
      KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_DATA_TEST }}
      MSSQL_BACKUP_USER: ${{ secrets.MSSQL_BACKUP_USER }}
      MSSQL_BACKUP_PASSWORD: ${{ secrets.MSSQL_BACKUP_PASSWORD }}
