name: Deploy to Prod

on:
  workflow_dispatch:

jobs:
  deploy-to-test:
    uses: ./.github/workflows/deploy-to-env.yml
    with:
      k8s_namespace: grif-prod
    secrets:
      KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_DATA_PROD }}
      MSSQL_BACKUP_USER: ${{ secrets.MSSQL_BACKUP_USER }}
      MSSQL_BACKUP_PASSWORD: ${{ secrets.MSSQL_BACKUP_PASSWORD }}
